### ISSUE TITLE
ModuleNotFoundError when install through pip

### ISSUE THREAD

**Issue by vishnuprksh** [Auto-Playground/ragrank#34]
Then following error pops when follow the basic evaluation page (https://ragrank.readthedocs.io/latest/get_started/basic_evaluation.html)
![image](https://github.com/Auto-Playground/ragrank/assets/119521719/161f24c8-c790-4b04-be12-016180017ced)

**Comment by izam-mohammed** [comment]
Solved it. I will take action from version 0.0.7 onwards.
