### ISSUE TITLE
ReadTimeoutError when try to evaluate using colab notebook

### ISSUE THREAD

**Issue by vishnuprksh** [Auto-Playground/ragrank#41]
**Describe the bug**
ReadTimeoutError happens when we try the Quickstart method in colab notebooks. It works in kaggle notebooks though.

**Screenshots**
![image](https://github.com/Auto-Playground/ragrank/assets/119521719/ceb8fb7b-661d-45fa-9807-3be2362c8898)

**Comment by izam-mohammed** [comment]
Solved the issue with this PR(#44)
