### ISSUE TITLE
API KEY error when using Colab Notebooks

### ISSUE THREAD

**Issue by vishnuprksh** [Auto-Playground/ragrank#42]
**Describe the bug**
The OPENAI_API_KEY is not working when we use colab notebooks. 

**To Reproduce**
Follow the quick start steps in colab notebooks.

**Expected behavior**
Use of OS module, seems to solve the issue. But I believe we should adapt some more general quick start method

**Comment by vishnuprksh** [comment]
the screenshot is wrong.

**Comment by izam-mohammed** [comment]
Thanks for posting this @vishnuprksh. It is not a problem of `OPENAI_API_KEY`. Setting environment variable procedure will differ from platforms. with the PR(#44), I have added additional steps in the documentation. checkout that in [here](ragrank.readthedocs.io)
