### ISSUE TITLE
What is the difference with ragas?

### ISSUE THREAD

**Issue by ogencoglu** [Auto-Playground/ragrank#47]
A detailed section in your docs or Readme would be helpful to understand how does ragrank differentiate with ragas. For example in terms of types of metrics or accuracy or latency or support for integrations?

**Comment by izam-mohammed** [comment]
Thanks again for the suggestion @ogencoglu . We will definitely add a comparison between ragrank and all of the other tools out there for evaluation (including ragas, uptrain, trulens, ...). it will be available from the next release of the package.
